/**
 * Hand-authored phrase library for combinatorial review assembly.
 * Every string here was written directly rather than generated by a live model call, so
 * generation has no external dependency and no per-request cost.
 */

export type RatingTier = "5" | "4" | "3";

// Ratings below 3 stars are never auto-generated (see pickWeightedRating in
// packages/shared/src/review-schemas.ts, which only offers POSITIVE/NEUTRAL sentiment) — a
// manually-edited review can still be set to 1-2 stars via the edit dialog, so this stays total
// rather than throwing, collapsing into the nearest tier's phrasing.
export function ratingToTier(rating: number): RatingTier {
  if (rating >= 5) return "5";
  if (rating === 4) return "4";
  return "3";
}

type Phrase = string; // may contain {productType}, {brandCategory}, {brandName} placeholders

export const OPENERS: Record<RatingTier, Phrase[]> = {
  "5": [
    "I honestly wasn't expecting much, but this blew me away.",
    "This might be my favorite purchase this year.",
    "I've already told three friends about this.",
    "Ordered on a whim and I'm so glad I did.",
    "This exceeded every expectation I had.",
    "I'm genuinely impressed from the moment I opened the box.",
    "Five stars, no hesitation.",
    "This is exactly what I didn't know I needed.",
    "I keep finding new things to love about this.",
    "Best purchase I've made in a while, hands down.",
    "I was skeptical at first, but this won me over completely.",
    "This has become part of my daily routine already.",
    "I almost didn't buy this, and now I regret waiting so long.",
    "This is one of those rare products that actually lives up to the hype.",
    "I'm already thinking about getting a second one.",
  ],
  "4": [
    "Really happy with this purchase overall.",
    "This has been a solid addition to my routine.",
    "I was pleasantly surprised by the quality.",
    "Good value for what you get.",
    "This has held up well so far.",
    "I'd recommend this to most people I know.",
    "Overall a great experience with this product.",
    "This does what it promises, and does it well.",
    "I've been using this for a few weeks now and I'm satisfied.",
    "A few small things aside, I'm happy with this.",
    "This was a smart buy for the price.",
    "I'm glad I picked this one over the alternatives I was considering.",
    "This has quickly become something I reach for often.",
    "Good quality and arrived exactly as described.",
    "I have minor nitpicks, but nothing that ruins the experience.",
  ],
  "3": [
    "This is a fine product, nothing more, nothing less.",
    "It does the job, though I expected a bit more.",
    "Mixed feelings about this one.",
    "It's okay — not amazing, not bad.",
    "This met some expectations but not all of them.",
    "Decent for the price, though I've seen better.",
    "I'm still deciding how I feel about this.",
    "It works fine, just didn't wow me.",
    "This is a reasonable choice if you're not picky.",
    "There are things I like and things I'd change.",
    "It's a middle-of-the-road product overall.",
    "Not bad, but I probably wouldn't buy it again.",
  ],
};

export const DETAILS: Record<RatingTier, Phrase[]> = {
  "5": [
    "The {productType} fits perfectly into my daily routine.",
    "Every detail on the {productType} feels well thought out.",
    "The quality of this {productType} is noticeably better than similar ones I've tried.",
    "It looks even better in person than in the photos.",
    "I've used this {productType} constantly since it arrived and it hasn't let me down once.",
    "The craftsmanship on this {productType} really stands out.",
    "It's clear a lot of care went into designing this {productType}.",
    "Shipping was fast and it arrived in perfect condition.",
    "The packaging alone made this {productType} feel like a premium product.",
    "I've compared this {productType} to others and this one wins easily.",
    "This {productType} is sturdier than I expected for the price.",
    "The little details on this {productType} make a big difference day to day.",
    "I appreciate how thoughtfully this {productType} was designed.",
    "This {productType} has genuinely made my routine easier.",
    "I keep noticing new things I like about this {productType} the more I use it.",
    "It's clear this brand knows {brandCategory} — this one really shows that.",
    "Compared to other {brandCategory} products I've tried, this one is a standout.",
  ],
  "4": [
    "The {productType} works well, though there's minor room for improvement.",
    "It arrived quickly and matched the description closely.",
    "This {productType} feels durable and well-made.",
    "I like most things about this {productType}, aside from a small learning curve.",
    "The build quality on this {productType} is better than I expected at this price point.",
    "This {productType} does its job reliably.",
    "It was easy to start using right away.",
    "I appreciate the design of this {productType}, even if it's not perfect.",
    "This {productType} has been consistent since day one.",
    "Compared to similar options, this {productType} holds its own.",
    "It looks great and functions just as well.",
    "The {productType} feels like it'll last a good while.",
    "Solid entry in the {brandCategory} space, worth considering.",
  ],
  "3": [
    "The {productType} works as described, nothing extra.",
    "It's fine for everyday use.",
    "This {productType} gets the job done without standing out.",
    "I think the price of this {productType} is fair, not a bargain.",
    "It matched the listing, at least.",
    "This {productType} is functional but a bit unremarkable.",
    "Nothing wrong with this {productType}, just nothing exceptional either.",
    "This {productType} is average compared to others I've owned.",
    "It does what it says, just without much flair.",
    "I'd call this {productType} a safe, unexciting choice.",
  ],
};

export const CLOSERS: Record<RatingTier, Phrase[]> = {
  "5": [
    "Would absolutely buy again.",
    "Highly recommend this to anyone on the fence.",
    "Already planning to order another one as a gift.",
    "This earned a permanent spot in my routine.",
    "Can't recommend this enough.",
    "Worth every penny.",
    "This is going straight into my regular rotation.",
    "I'll be back for more from this shop.",
  ],
  "4": [
    "Would recommend, with just a couple small caveats.",
    "Happy to have found this one.",
    "Would consider buying again.",
    "A solid choice overall.",
    "Glad I gave this a try.",
    "Worth it for the price.",
  ],
  "3": [
    "Might try something else next time, but this works for now.",
    "It's fine — wouldn't go out of my way to recommend it.",
    "An okay option if you're not expecting much.",
    "Neutral on whether I'd repurchase.",
    "Serviceable, but not memorable.",
  ],
};

/** Brand-name-referencing closers, only for positive tiers — swapped in occasionally when a
 * store has Brand Settings configured. Contains a {brandName} placeholder. */
export const BRAND_CLOSERS: Record<"5" | "4", Phrase[]> = {
  "5": [
    "I'll definitely be shopping at {brandName} again.",
    "{brandName} has earned a loyal customer with this one.",
    "This is exactly the kind of quality I've come to expect from {brandName}.",
    "Already recommended {brandName} to a few friends because of this.",
  ],
  "4": [
    "Overall a good experience with {brandName}.",
    "{brandName} delivered on this one.",
    "Would shop with {brandName} again.",
  ],
};

/** USP/competitive-edge-referencing closers, only for positive tiers — swapped in occasionally
 * when a store has a Brand Settings USP configured. Contains {usp} and {brandName} placeholders;
 * {usp} is expected to read as a continuation of "this brand ___" (e.g. "uses recycled packaging"). */
export const USP_CLOSERS: Record<"5" | "4", Phrase[]> = {
  "5": [
    "What really won me over is that this brand {usp}.",
    "Love that {brandName} {usp} — that's a big reason I keep coming back.",
    "Not many brands {usp}, which makes this one stand out from the rest.",
  ],
  "4": [
    "It's nice that this brand {usp}.",
    "Appreciate that {brandName} {usp}.",
  ],
};

/** Used when the reviewer's own gender doesn't match the product's detected audience (e.g. a
 * male reviewer on a women's chain) — frames the purchase as a gift instead of personal use, via
 * a {giftRecipient} placeholder (see `pickGiftRecipient` in @ai-shopify/shared). */
export const GIFT_OPENERS: Record<RatingTier, Phrase[]> = {
  "5": [
    "I picked this up as a gift for my {giftRecipient} and it was a huge hit.",
    "Got this for my {giftRecipient}, and it turned out to be perfect.",
    "This was a gift for my {giftRecipient}, who absolutely loves it.",
    "Bought this for my {giftRecipient} and honestly nailed it with this one.",
  ],
  "4": [
    "Picked this up as a gift for my {giftRecipient}, who's been happy with it.",
    "Got this for my {giftRecipient} and it's gone over well.",
    "This was a gift for my {giftRecipient} — pretty solid choice overall.",
  ],
  "3": [
    "Got this as a gift for my {giftRecipient} — mixed feelings from them, honestly.",
    "Picked this up for my {giftRecipient}. It's fine, nothing special.",
  ],
};

export const GIFT_DETAILS: Record<RatingTier, Phrase[]> = {
  "5": [
    "My {giftRecipient} says the {productType} is even better than expected.",
    "The quality of this {productType} really impressed my {giftRecipient}.",
    "My {giftRecipient} has been using this {productType} constantly since I gave it to them.",
    "It's clear a lot of care went into this {productType} — my {giftRecipient} noticed right away.",
  ],
  "4": [
    "My {giftRecipient} likes the {productType}, aside from a small learning curve.",
    "The {productType} arrived quickly and matched what I expected for my {giftRecipient}.",
    "My {giftRecipient} says this {productType} feels durable and well-made.",
  ],
  "3": [
    "My {giftRecipient} says the {productType} works as described, nothing extra.",
    "It's a fine {productType} for my {giftRecipient}, nothing that stood out either way.",
  ],
};

export const GIFT_CLOSERS: Record<RatingTier, Phrase[]> = {
  "5": [
    "Already thinking about getting one for someone else too.",
    "Definitely coming back here for future gifts.",
    "Would absolutely buy this as a gift again.",
  ],
  "4": ["Happy I went with this as a gift.", "Would consider buying this as a gift again."],
  "3": ["Might look elsewhere next time I need a gift like this.", "An okay gift option, nothing more."],
};

export const TITLE_PHRASES: Record<RatingTier, Phrase[]> = {
  "5": [
    "Exceeded my expectations",
    "Absolutely love this",
    "Best purchase in a while",
    "Highly recommend",
    "Worth every penny",
    "Exactly what I needed",
    "Impressed with the quality",
  ],
  "4": [
    "Really happy with this",
    "Solid choice",
    "Good value overall",
    "Pleasantly surprised",
    "Would recommend",
    "Great addition to my routine",
  ],
  "3": [
    "It's okay",
    "Does the job",
    "Average, but functional",
    "Mixed feelings",
    "Fair for the price",
  ],
};

export const FEMALE_FIRST_NAMES = [
  "Priya", "Lakshmi", "Divya", "Kavya", "Meena", "Anitha", "Deepika", "Swathi", "Ramya", "Sneha",
  "Pooja", "Nithya", "Aishwarya", "Radhika", "Shreya", "Vidya", "Bhavana", "Keerthana", "Anjali",
  "Suchitra", "Padma", "Revathi", "Gayathri", "Sowmya", "Vaishnavi", "Harini", "Sindhu", "Roja",
  "Malini", "Uma",
];

export const MALE_FIRST_NAMES = [
  "Ravi", "Kiran", "Suresh", "Arjun", "Karthik", "Naveen", "Vijay", "Prakash", "Ganesh", "Srinivas",
  "Ramesh", "Anand", "Manoj", "Sathish", "Venkat", "Praveen", "Dinesh", "Mahesh", "Rajesh", "Vikram",
  "Krishna", "Aravind", "Balaji", "Chandran", "Gopal", "Hari", "Jayakumar", "Kumar", "Madhavan",
  "Naresh",
];

export const LAST_NAMES = [
  "Iyer", "Iyengar", "Reddy", "Naidu", "Nair", "Menon", "Pillai", "Gowda", "Rao", "Shetty",
  "Chettiar", "Achari", "Rajan", "Subramaniam", "Krishnan", "Venkataraman", "Balasubramaniam",
  "Chandrasekaran", "Ramanathan", "Varma", "Acharya", "Bhat", "Kamath", "Shenoy", "Hegde", "Pai",
  "Prabhu", "Nadar", "Mudaliar", "Pandian",
];

export const COUNTRIES = ["India"];

export const AGE_GROUPS = ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"];

export const OCCUPATIONS = [
  "Teacher", "Nurse", "Software Engineer", "Graphic Designer", "Small Business Owner",
  "Marketing Manager", "Student", "Freelance Writer", "Accountant", "Chef",
  "Photographer", "Retail Manager", "Physical Therapist", "Consultant", "Stay-at-Home Parent",
  "Sales Representative", "Architect", "Electrician", "Real Estate Agent", "Personal Trainer",
];
